name = "MLJTSVDInterface"
uuid = "7fa162e1-0e29-41ca-a6fa-c000ca4e7e7e"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>", "Chris Alexander <uvapazzo@gmail.com>"]
version = "0.1.0"

[deps]
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
ScientificTypesBase = "30f210dd-8aff-4c5f-94ba-8e64358c1161"
TSVD = "9449cd9e-2762-5aa3-a617-5413e99d722e"

[compat]
MLJModelInterface = "1.1.1"
ScientificTypesBase = "1"
TSVD = "0.4.3"
julia = "1"

[extras]
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distributions", "MLJBase", "StableRNGs", "Test"]
